# Generated by Django 3.0.2 on 2020-02-15 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('host', models.URLField()),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('displayName', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
    ]
